### ISSUE TITLE
500 ошибка на странице Woocommerce > Настройки Робокассы

### ISSUE THREAD

**Issue by AlbertRAR** [ipolh/woocommerce_robokassa#1]
Привет,
активировал плагин, перешел во вкладку Настройки Робокассы, а страница пустая. 
В консоли след. ошибка:
`Failed to load resource: the server responded with a status of 500 () admin.php?page=main_settings_rb.php:1 `

**Comment by ipolh** [comment]
Добрый день!
Попробуйте обновить модуль, был большой рефакторинг

**Comment by AlbertRAR** [comment]
Ошибка никуда не делась.
