### ISSUE TITLE
Добавьте функционал

### ISSUE THREAD

**Issue by infosebel** [ipolh/woocommerce_robokassa#3]
1. Настройка называется “Удалить товары из корзины, когда покупатель переходит к оплате”.
Т.к. после оплаты woocommerce не понимает, что надо товары из корзины удалять и оставляет их.

2. Также ваш модуль не работает на версии php 7.2

**Comment by ipolh** [comment]
Добрый день!
Вынесли на обсуждение доработку (п1)
поддержка php 7.1.x ~ 7.3.x планируется в ближайшем будущем

**Comment by AlbertRAR** [comment]
Здравствуйте!
Когда планируется реализовать 1-й пункт? Это очень важная и нужная вещь.

**Comment by AlbertRAR** [comment]
А почему вы вопросы оставляете без ответов и закрываете?

**Comment by ipolh** [comment]
Добрый день!
Мы закрываем тикеты только в случае обновления функционала. Данный тикет был решен коммитом 22064aab71049c8ab132942b7aeaf9302b190cde

**Comment by AlbertRAR** [comment]
Понятно, это хорошо! Просто когда вы закрываете таск "тихо", оставалось только догадываться о причине закрытия)
